---
title: "Instacart Flexdashboard: Recently Reordered Items in the Deli Department"
output:   
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, message = FALSE, warning = FALSE, include = FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```


```{r insta, message = FALSE, include = FALSE}
##Here,  I'm loading in my instacart data, which will be used to make a flexdashboard of various visualizations of the data. 

##I then clean the data by:

##- using `select` to only include the variables of interest: product name, aisle, department, days since prior order, if the item was reordered, order hour of day, and order id
##- filtering to only reordered items, those in the deli department, and orders within 3 weeks of the last order

data("instacart")

insta = instacart %>% 
  select(product_name, aisle, department, days_since_prior_order, reordered, order_hour_of_day, order_id)  %>% 
  filter(reordered == 1,
         department ==  "deli",
         days_since_prior_order < 22)  
```
 
Column {data-width=550}
-----------------------------------------------------------------------

### Bar plot

```{r bar_plot}

insta %>%   
  count(product_name) %>% 
  filter(n > 225) %>% 
  mutate(product_name =  fct_reorder(product_name, n)) %>% 
  plot_ly(x = ~product_name, y = ~n, color = ~product_name, type = "bar", colors = "viridis") %>% 
  layout(plot_bgcolor = "f8f8f8",
         xaxis = list(title = "Product name", tickfont = list(size = 11)), 
         yaxis = list(title = "Numer ordered"), 
         title = "Most popular recently reordered deli department items",  
         titlefont = list(size = 16),
         showlegend = FALSE)

```

Column {data-width=450}
-----------------------------------------------------------------------

### Line plot 

```{r line_plot}

## I had to format the names oddly so I could fit my key without covering plot

insta_line_a = insta %>%   
  filter(aisle == "lunch meat") %>% 
  count(days_since_prior_order)  %>%
  ungroup() %>%
  plot_ly(x = ~days_since_prior_order, y = ~n, name = "Lunch 
meat", type = "scatter", 
          mode = "lines+markers", marker = list(color = "778a35"), 
          line = list(color = "778a35", width = 4)) %>% 
  layout(plot_bgcolor = "fffefa") 

insta_line_b = insta %>%   
  filter(aisle == "prepared meals") %>% 
  count(days_since_prior_order)  %>%
  ungroup() %>%
  plot_ly(x = ~days_since_prior_order, y = ~n, name = 'Prepared 
meals', type = "scatter", 
          mode = "lines+markers", marker = list(color = "gold"), 
          line = list(color = "gold", width = 4))  %>% 
  layout(plot_bgcolor = "fffefa") 

insta_line_c = insta %>%   
  filter(aisle == "fresh dips tapenades") %>% 
  count(days_since_prior_order)  %>%
  ungroup() %>%
  plot_ly(x = ~days_since_prior_order, y = ~n, name = 'Fresh 
dips &
tapenades', type = "scatter", 
          mode = "lines+markers", marker = list(color = "a7a6ba"), line = list(color = "a7a6ba", width = 4)) %>% 
  layout(plot_bgcolor = "fffefa") 

insta_line = subplot(insta_line_b, insta_line_a, insta_line_c, nrows = 3) %>%
  layout(xaxis3 = list(title = "Days since prior order"), 
         yaxis2 = list(title = "# orders"),
         title = list(text = "Days since last order for recently reordered items in three aisles"), 
         titlefont = list(size = 14),
         legend = list(font = list(size = 10)))

insta_line 

```

### Scatter plot 

```{r scatter_plot}

insta %>% 
  filter(order_id < 11000) %>% 
  plot_ly(x = ~jitter(days_since_prior_order, 1), y = ~jitter(order_hour_of_day, 1), type = "scatter", mode = "markers",
    color = ~product_name, hovertemplate = ~product_name, alpha = 0.5, colors = "#feffee", showlegend = FALSE) %>% 
  layout(plot_bgcolor = "333366",
         xaxis = list(title = "Days since prior order"), 
         yaxis = list(title = "Order hour of day"), 
         title = "Order hour and days since last order for recent deli reorders",  
         titlefont = list(size = 14))

```

